import { Router } from 'express';
import { pool } from '../data/db.js';
import { requireAuth } from '../middleware/auth.js';

const router = Router({ mergeParams: true });
router.use(requireAuth);

async function assertEvent(req) {
  const { eventId } = req.params;
  const r = await pool.query('SELECT "EventId", "OrganizationId" FROM "Event" WHERE "EventId" = $1 AND "IsDeleted" = false', [eventId]);
  if (!r.rowCount || String(r.rows[0].OrganizationId) !== String(req.user.organizationId)) {
    const err = new Error('Event not found.'); err.status = 404; throw err;
  }
  return r.rows[0];
}

function rows(r) { return r.rows; }
function row(r) { return r.rows[0] || null; }
function iso(v) { return v || null; }

// Announcements
router.get('/announcements', async (req, res, next) => { try { await assertEvent(req); const r = await pool.query(`SELECT * FROM "Announcements" WHERE "EventId"=$1 AND "IsDeleted"=false ORDER BY "Priority" DESC, "CreatedAt" DESC`, [req.params.eventId]); res.json(rows(r)); } catch(e){next(e);} });
router.post('/announcements', async (req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "Announcements" ("EventId","Title","Content","Summary","AnnouncementType","Priority","TargetAudience","TargetSegmentsJson","IsPushNotification","IsEmail","IsInApp","IsPublished","PublishedAt","ExpiresAt","ActionButtonText","ActionButtonUrl","CreatedByPersonId") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,CASE WHEN $12 THEN (now() AT TIME ZONE 'utc') ELSE (now() AT TIME ZONE 'utc') END,$13,$14,$15,$16) RETURNING *`,[req.params.eventId,b.title,b.content,b.summary||null,b.announcementType||'General',Number(b.priority)||1,b.targetAudience||'All',b.targetSegmentsJson||null,!!b.isPushNotification,!!b.isEmail,b.isInApp!==false,b.isPublished!==false,b.expiresAt||null,b.actionButtonText||null,b.actionButtonUrl||null,req.user.sub]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/announcements/:id', async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const fields={title:'Title',content:'Content',summary:'Summary',announcementType:'AnnouncementType',priority:'Priority',targetAudience:'TargetAudience',targetSegmentsJson:'TargetSegmentsJson',isPushNotification:'IsPushNotification',isEmail:'IsEmail',isInApp:'IsInApp',isPublished:'IsPublished',expiresAt:'ExpiresAt',actionButtonText:'ActionButtonText',actionButtonUrl:'ActionButtonUrl'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const [k,c] of Object.entries(fields)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}if(b.isPublished===true)sets.push(`"PublishedAt"=(now() AT TIME ZONE 'utc')`);if(!sets.length)return res.status(400).json({error:'No changes supplied.'});const r=await pool.query(`UPDATE "Announcements" SET ${sets.join(', ')} WHERE "EventId"=$1 AND "AnnouncementId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Announcement not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/announcements/:id', async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "Announcements" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "AnnouncementId"=$2 AND "IsDeleted"=false RETURNING "AnnouncementId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Announcement not found.'});res.json({ok:true});}catch(e){next(e);}});

// Meet-ups
router.get('/meetups', async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`SELECT * FROM "Meetups" WHERE "EventId"=$1 AND "IsDeleted"=false ORDER BY "StartTime"`,[req.params.eventId]);res.json(rows(r));}catch(e){next(e);}});
router.post('/meetups',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "Meetups" ("EventId","OrganizerPersonId","Title","Description","MeetupType","Location","VirtualMeetingUrl","StartTime","EndTime","MaxAttendees","IsPrivate","AccessCode","Status") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.params.eventId,req.user.sub,b.title,b.description||null,b.meetupType||'Virtual',b.location||null,b.virtualMeetingUrl||null,b.startTime,b.endTime,b.maxAttendees?Number(b.maxAttendees):null,!!b.isPrivate,b.accessCode||null,b.status||'Scheduled']);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/meetups/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={title:'Title',description:'Description',meetupType:'MeetupType',location:'Location',virtualMeetingUrl:'VirtualMeetingUrl',startTime:'StartTime',endTime:'EndTime',maxAttendees:'MaxAttendees',isPrivate:'IsPrivate',accessCode:'AccessCode',status:'Status'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}sets.push(`"UpdatedAt"=(now() AT TIME ZONE 'utc')`);const r=await pool.query(`UPDATE "Meetups" SET ${sets.join(',')} WHERE "EventId"=$1 AND "MeetupId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Meet-up not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/meetups/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "Meetups" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "MeetupId"=$2 AND "IsDeleted"=false RETURNING "MeetupId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Meet-up not found.'});res.json({ok:true});}catch(e){next(e);}});

// Discussion topics
router.get('/discussion-topics',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`SELECT d.*, COALESCE(p."FullName", p."Email", 'Admin') AS "CreatedByName" FROM "DiscussionTopics" d LEFT JOIN "Person" p ON p."PersonId"=d."CreatedByPersonId" WHERE d."EventId"=$1 AND d."IsDeleted"=false ORDER BY d."IsPinned" DESC,d."CreatedAt" DESC`,[req.params.eventId]);res.json(rows(r));}catch(e){next(e);}});
router.post('/discussion-topics',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "DiscussionTopics" ("EventId","CreatedByPersonId","Title","Content","Category","IsPinned","IsLocked","IsApproved","Tags") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[req.params.eventId,req.user.sub,b.title,b.content,b.category||null,!!b.isPinned,!!b.isLocked,b.isApproved!==false,b.tags||null]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/discussion-topics/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={title:'Title',content:'Content',category:'Category',isPinned:'IsPinned',isLocked:'IsLocked',isApproved:'IsApproved',tags:'Tags'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}sets.push(`"UpdatedAt"=(now() AT TIME ZONE 'utc')`);const r=await pool.query(`UPDATE "DiscussionTopics" SET ${sets.join(',')} WHERE "EventId"=$1 AND "TopicId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Discussion topic not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/discussion-topics/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "DiscussionTopics" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "TopicId"=$2 AND "IsDeleted"=false RETURNING "TopicId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Discussion topic not found.'});res.json({ok:true});}catch(e){next(e);}});

// Social groups
router.get('/social-groups',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`SELECT * FROM "SocialGroups" WHERE "EventId"=$1 AND "IsDeleted"=false ORDER BY "CreatedAt" DESC`,[req.params.eventId]);res.json(rows(r));}catch(e){next(e);}});
router.post('/social-groups',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "SocialGroups" ("EventId","OwnerPersonId","Name","Description","GroupType","Privacy","AccessCode","AvatarUrl","CoverImageUrl","IsActive") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.params.eventId,req.user.sub,b.name,b.description||null,b.groupType||'Interest',b.privacy||'Public',b.accessCode||null,b.avatarUrl||null,b.coverImageUrl||null,b.isActive!==false]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/social-groups/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={name:'Name',description:'Description',groupType:'GroupType',privacy:'Privacy',accessCode:'AccessCode',avatarUrl:'AvatarUrl',coverImageUrl:'CoverImageUrl',isActive:'IsActive'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}sets.push(`"UpdatedAt"=(now() AT TIME ZONE 'utc')`);const r=await pool.query(`UPDATE "SocialGroups" SET ${sets.join(',')} WHERE "EventId"=$1 AND "GroupId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Social group not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/social-groups/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "SocialGroups" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "GroupId"=$2 AND "IsDeleted"=false RETURNING "GroupId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Social group not found.'});res.json({ok:true});}catch(e){next(e);}});

// Gamification: event badges + global action catalog
router.get('/gamification',async(req,res,next)=>{try{await assertEvent(req);const [a,b]=await Promise.all([pool.query(`SELECT * FROM "GamificationActions" WHERE "IsDeleted"=false ORDER BY "ActionName"`),pool.query(`SELECT * FROM "Badges" WHERE "EventId"=$1 AND "IsDeleted"=false ORDER BY "SortOrder","BadgeName"`,[req.params.eventId])]);res.json({actions:a.rows,badges:b.rows});}catch(e){next(e);}});
router.post('/gamification/actions',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "GamificationActions" ("ActionKey","ActionName","DefaultPoints","MaxDaily","CooldownMinutes","Description") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`,[b.actionKey,b.actionName,Number(b.defaultPoints)||0,b.maxDaily?Number(b.maxDaily):null,b.cooldownMinutes?Number(b.cooldownMinutes):null,b.description||null]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/gamification/actions/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={actionKey:'ActionKey',actionName:'ActionName',defaultPoints:'DefaultPoints',maxDaily:'MaxDaily',cooldownMinutes:'CooldownMinutes',description:'Description'};const sets=[];const vals=[req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}if(!sets.length)return res.status(400).json({error:'No changes supplied.'});const r=await pool.query(`UPDATE "GamificationActions" SET ${sets.join(',')} WHERE "ActionId"=$1 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Action not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/gamification/actions/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "GamificationActions" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$2 WHERE "ActionId"=$1 AND "IsDeleted"=false RETURNING "ActionId"`,[req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Action not found.'});res.json({ok:true});}catch(e){next(e);}});
router.post('/gamification/badges',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "Badges" ("EventId","BadgeName","Description","BadgeIcon","BadgeColor","CriteriaType","CriteriaValue","PointsReward","IsHidden","SortOrder") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.params.eventId,b.badgeName,b.description||null,b.badgeIcon||null,b.badgeColor||null,b.criteriaType||'Points',Number(b.criteriaValue)||0,Number(b.pointsReward)||0,!!b.isHidden,Number(b.sortOrder)||0]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/gamification/badges/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={badgeName:'BadgeName',description:'Description',badgeIcon:'BadgeIcon',badgeColor:'BadgeColor',criteriaType:'CriteriaType',criteriaValue:'CriteriaValue',pointsReward:'PointsReward',isHidden:'IsHidden',sortOrder:'SortOrder'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}const r=await pool.query(`UPDATE "Badges" SET ${sets.join(',')} WHERE "EventId"=$1 AND "BadgeId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Badge not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/gamification/badges/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "Badges" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "BadgeId"=$2 AND "IsDeleted"=false RETURNING "BadgeId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Badge not found.'});res.json({ok:true});}catch(e){next(e);}});

// Surveys + Session Feedback (PostSession templates use the same builder)
async function listSurveys(req,res,next,feedbackOnly=false){try{await assertEvent(req);const where=feedbackOnly?` AND s."SurveyType"='PostSession'`:'';const r=await pool.query(`SELECT s.*, se."Title" AS "SessionTitle", COALESCE((SELECT count(*) FROM "SurveyQuestions" q WHERE q."SurveyTemplateId"=s."SurveyTemplateId"),0)::int AS "QuestionCount" FROM "SurveyTemplates" s LEFT JOIN "Sessions" se ON se."SessionId"=s."SessionId" WHERE s."EventId"=$1 ${where} ORDER BY s."CreatedAt" DESC`,[req.params.eventId]);res.json(rows(r));}catch(e){next(e);}}
router.get('/surveys',(req,res,next)=>listSurveys(req,res,next,false));
router.get('/session-feedback',(req,res,next)=>listSurveys(req,res,next,true));
router.post('/surveys',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "SurveyTemplates" ("EventId","SessionId","Title","Description","SurveyType","IsAnonymous","IsActive","OpensAt","ClosesAt","CreatedByPersonId") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.params.eventId,b.sessionId||null,b.title,b.description||null,b.surveyType||'Custom',!!b.isAnonymous,b.isActive!==false,b.opensAt||null,b.closesAt||null,req.user.sub]);const id=r.rows[0].SurveyTemplateId;if(Array.isArray(b.questions)){for(let i=0;i<b.questions.length;i++){const q=b.questions[i];const qr=await pool.query(`INSERT INTO "SurveyQuestions" ("SurveyTemplateId","QuestionText","QuestionType","IsRequired","SortOrder","MinRating","MaxRating") VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING "SurveyQuestionId"`,[id,q.questionText,q.questionType||'Text',!!q.isRequired,i,q.minRating??null,q.maxRating??null]);if(Array.isArray(q.options)){for(let j=0;j<q.options.length;j++)await pool.query(`INSERT INTO "SurveyQuestionOptions" ("SurveyQuestionId","Label","SortOrder") VALUES ($1,$2,$3)`,[qr.rows[0].SurveyQuestionId,q.options[j],j]);}}}res.status(201).json(r.rows[0]);}catch(e){next(e);}});
router.get('/surveys/:id',async(req,res,next)=>{try{await assertEvent(req);const s=await pool.query(`SELECT s.*, se."Title" AS "SessionTitle" FROM "SurveyTemplates" s LEFT JOIN "Sessions" se ON se."SessionId"=s."SessionId" WHERE s."EventId"=$1 AND s."SurveyTemplateId"=$2`,[req.params.eventId,req.params.id]);if(!s.rowCount)return res.status(404).json({error:'Survey not found.'});const q=await pool.query(`SELECT q.*, COALESCE(json_agg(json_build_object('optionId',o."OptionId",'label',o."Label") ORDER BY o."SortOrder") FILTER (WHERE o."OptionId" IS NOT NULL),'[]') AS "Options" FROM "SurveyQuestions" q LEFT JOIN "SurveyQuestionOptions" o ON o."SurveyQuestionId"=q."SurveyQuestionId" WHERE q."SurveyTemplateId"=$1 GROUP BY q."SurveyQuestionId" ORDER BY q."SortOrder"`,[req.params.id]);res.json({...s.rows[0],questions:q.rows});}catch(e){next(e);}});
router.patch('/surveys/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={sessionId:'SessionId',title:'Title',description:'Description',surveyType:'SurveyType',isAnonymous:'IsAnonymous',isActive:'IsActive',opensAt:'OpensAt',closesAt:'ClosesAt'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}sets.push(`"UpdatedAt"=(now() AT TIME ZONE 'utc')`);const r=await pool.query(`UPDATE "SurveyTemplates" SET ${sets.join(',')} WHERE "EventId"=$1 AND "SurveyTemplateId"=$2 RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Survey not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/surveys/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`DELETE FROM "SurveyTemplates" WHERE "EventId"=$1 AND "SurveyTemplateId"=$2 RETURNING "SurveyTemplateId"`,[req.params.eventId,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Survey not found.'});res.json({ok:true});}catch(e){next(e);}});

// Floormap
router.get('/floormaps',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`SELECT f.*, COALESCE((SELECT count(*) FROM "FloorMapMarkers" m WHERE m."FloorMapId"=f."FloorMapId" AND m."IsDeleted"=false),0)::int AS "MarkerCount" FROM "FloorMaps" f WHERE f."EventId"=$1 AND f."IsDeleted"=false ORDER BY f."SortOrder",f."Name"`,[req.params.eventId]);res.json(rows(r));}catch(e){next(e);}});
router.post('/floormaps',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "FloorMaps" ("EventId","Name","Description","FloorLevel","ImageUrl","ThumbnailUrl","Width","Height","IsActive","SortOrder") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.params.eventId,b.name,b.description||null,b.floorLevel||null,b.imageUrl,b.thumbnailUrl||null,b.width||null,b.height||null,b.isActive!==false,Number(b.sortOrder)||0]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/floormaps/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={name:'Name',description:'Description',floorLevel:'FloorLevel',imageUrl:'ImageUrl',thumbnailUrl:'ThumbnailUrl',width:'Width',height:'Height',isActive:'IsActive',sortOrder:'SortOrder'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}sets.push(`"UpdatedAt"=(now() AT TIME ZONE 'utc')`);const r=await pool.query(`UPDATE "FloorMaps" SET ${sets.join(',')} WHERE "EventId"=$1 AND "FloorMapId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Floormap not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/floormaps/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "FloorMaps" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "FloorMapId"=$2 AND "IsDeleted"=false RETURNING "FloorMapId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Floormap not found.'});res.json({ok:true});}catch(e){next(e);}});
router.get('/floormaps/:id/markers',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`SELECT m.* FROM "FloorMapMarkers" m JOIN "FloorMaps" f ON f."FloorMapId"=m."FloorMapId" WHERE f."EventId"=$1 AND m."FloorMapId"=$2 AND m."IsDeleted"=false ORDER BY m."SortOrder",m."Title"`,[req.params.eventId,req.params.id]);res.json(rows(r));}catch(e){next(e);}});
router.post('/floormaps/:id/markers',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "FloorMapMarkers" ("FloorMapId","MarkerType","EntityId","Title","Description","XCoord","YCoord","IconUrl","IconColor","TooltipText","LinkUrl","PopupContent","SortOrder") SELECT $2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14 WHERE EXISTS (SELECT 1 FROM "FloorMaps" WHERE "FloorMapId"=$2 AND "EventId"=$1 AND "IsDeleted"=false) RETURNING *`,[req.params.eventId,req.params.id,b.markerType||'Custom',b.entityId||null,b.title,b.description||null,Number(b.xCoord)||0,Number(b.yCoord)||0,b.iconUrl||null,b.iconColor||null,b.tooltipText||null,b.linkUrl||null,b.popupContent||null,Number(b.sortOrder)||0]);if(!r.rowCount)return res.status(404).json({error:'Floormap not found.'});res.status(201).json(row(r));}catch(e){next(e);}});
router.delete('/floormaps/:mapId/markers/:markerId',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "FloorMapMarkers" m SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$4 FROM "FloorMaps" f WHERE m."MarkerId"=$2 AND m."FloorMapId"=$3 AND f."FloorMapId"=m."FloorMapId" AND f."EventId"=$1 RETURNING m."MarkerId"`,[req.params.eventId,req.params.markerId,req.params.mapId,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Marker not found.'});res.json({ok:true});}catch(e){next(e);}});

// Live polling
router.get('/live-polls',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`SELECT p.*, s."Title" AS "SessionTitle", COALESCE((SELECT json_agg(json_build_object('optionId',o."OptionId",'optionText',o."OptionText",'responseCount',o."ResponseCount") ORDER BY o."SortOrder") FROM "PollOptions" o WHERE o."PollId"=p."PollId"),'[]') AS "Options" FROM "LivePolls" p LEFT JOIN "Sessions" s ON s."SessionId"=p."SessionId" WHERE p."EventId"=$1 AND p."IsDeleted"=false ORDER BY p."CreatedAt" DESC`,[req.params.eventId]);res.json(rows(r));}catch(e){next(e);}});
router.post('/live-polls',async(req,res,next)=>{const client=await pool.connect();try{await assertEvent(req);const b=req.body||{};await client.query('BEGIN');const r=await client.query(`INSERT INTO "LivePolls" ("EventId","SessionId","CreatedByPersonId","Question","Description","PollType","IsAnonymous","IsActive","AllowMultipleAnswers","ShowResults","ResultsVisibility","StartsAt","EndsAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.params.eventId,b.sessionId||null,req.user.sub,b.question,b.description||null,b.pollType||'SingleChoice',!!b.isAnonymous,!!b.isActive,!!b.allowMultipleAnswers,b.showResults!==false,b.resultsVisibility||'AfterVote',b.startsAt||null,b.endsAt||null]);for(let i=0;i<(b.options||[]).length;i++){const o=b.options[i];if(String(o).trim())await client.query(`INSERT INTO "PollOptions" ("PollId","OptionText","OptionValue","SortOrder") VALUES ($1,$2,$3,$4)`,[r.rows[0].PollId,String(o).trim(),String(o).trim(),i]);}await client.query('COMMIT');res.status(201).json(r.rows[0]);}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});
router.patch('/live-polls/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={question:'Question',description:'Description',pollType:'PollType',isAnonymous:'IsAnonymous',isActive:'IsActive',allowMultipleAnswers:'AllowMultipleAnswers',showResults:'ShowResults',resultsVisibility:'ResultsVisibility',startsAt:'StartsAt',endsAt:'EndsAt',sessionId:'SessionId'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}const r=await pool.query(`UPDATE "LivePolls" SET ${sets.join(',')} WHERE "EventId"=$1 AND "PollId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Poll not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/live-polls/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "LivePolls" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "PollId"=$2 AND "IsDeleted"=false RETURNING "PollId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Poll not found.'});res.json({ok:true});}catch(e){next(e);}});
router.patch('/live-polls/:id/options',async(req,res,next)=>{const client=await pool.connect();try{await assertEvent(req);await client.query('BEGIN');const r=await client.query(`SELECT "PollId" FROM "LivePolls" WHERE "EventId"=$1 AND "PollId"=$2 AND "IsDeleted"=false`,[req.params.eventId,req.params.id]);if(!r.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Poll not found.'});}await client.query(`DELETE FROM "PollOptions" WHERE "PollId"=$1`,[req.params.id]);for(let i=0;i<(req.body?.options||[]).length;i++){const o=req.body.options[i];if(String(o).trim())await client.query(`INSERT INTO "PollOptions" ("PollId","OptionText","OptionValue","SortOrder") VALUES ($1,$2,$3,$4)`,[req.params.id,String(o).trim(),String(o).trim(),i]);}await client.query('COMMIT');res.json({ok:true});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});

// Photos / media galleries
router.get('/photos',async(req,res,next)=>{try{await assertEvent(req);const [g,i]=await Promise.all([pool.query(`SELECT * FROM "MediaGalleries" WHERE "EventId"=$1 AND "IsDeleted"=false ORDER BY "SortOrder","GalleryName"`,[req.params.eventId]),pool.query(`SELECT * FROM "MediaItems" WHERE "EventId"=$1 AND "IsDeleted"=false ORDER BY "CreatedAt" DESC`,[req.params.eventId])]);res.json({galleries:g.rows,items:i.rows});}catch(e){next(e);}});
router.post('/photos/galleries',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "MediaGalleries" ("EventId","GalleryName","Description","CoverImageUrl","IsActive","SortOrder") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`,[req.params.eventId,b.galleryName,b.description||null,b.coverImageUrl||null,b.isActive!==false,Number(b.sortOrder)||0]);res.status(201).json(row(r));}catch(e){next(e);}});
router.patch('/photos/galleries/:id',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const map={galleryName:'GalleryName',description:'Description',coverImageUrl:'CoverImageUrl',isActive:'IsActive',sortOrder:'SortOrder'};const sets=[];const vals=[req.params.eventId,req.params.id];for(const[k,c]of Object.entries(map)){if(b[k]!==undefined){sets.push(`"${c}"=$${vals.length+1}`);vals.push(b[k]);}}const r=await pool.query(`UPDATE "MediaGalleries" SET ${sets.join(',')} WHERE "EventId"=$1 AND "GalleryId"=$2 AND "IsDeleted"=false RETURNING *`,vals);if(!r.rowCount)return res.status(404).json({error:'Gallery not found.'});res.json(row(r));}catch(e){next(e);}});
router.delete('/photos/galleries/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "MediaGalleries" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$3 WHERE "EventId"=$1 AND "GalleryId"=$2 AND "IsDeleted"=false RETURNING "GalleryId"`,[req.params.eventId,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Gallery not found.'});res.json({ok:true});}catch(e){next(e);}});
router.post('/photos/items',async(req,res,next)=>{try{await assertEvent(req);const b=req.body||{};const r=await pool.query(`INSERT INTO "MediaItems" ("GalleryId","EventId","MediaType","Title","Description","AltText","FileUrl","ThumbnailUrl","FileSize","MimeType","Width","Height","UploadedByPersonId","IsPublished","SortOrder") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[b.galleryId||null,req.params.eventId,b.mediaType||'Image',b.title||'Photo',b.description||null,b.altText||null,b.fileUrl,b.thumbnailUrl||null,b.fileSize?Number(b.fileSize):null,b.mimeType||null,b.width?Number(b.width):null,b.height?Number(b.height):null,req.user.sub,b.isPublished!==false,Number(b.sortOrder)||0]);res.status(201).json(row(r));}catch(e){next(e);}});
router.delete('/photos/items/:id',async(req,res,next)=>{try{await assertEvent(req);const r=await pool.query(`UPDATE "MediaItems" SET "IsDeleted"=true,"DeletedAt"=(now() AT TIME ZONE 'utc'),"DeletedBy"=$2 WHERE "EventId"=$1 AND "MediaItemId"=$3 AND "IsDeleted"=false RETURNING "MediaItemId"`,[req.params.eventId,req.user.sub,req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Photo not found.'});res.json({ok:true});}catch(e){next(e);}});

export default router;
